### ISSUE TITLE
Twitter share count has been deprecated

### ISSUE THREAD

**Issue by codenameyau** [newsela/sharing-metrics#2]
```javascript
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at parseTwitterShares (/Users/yau/Workspace/appleseed/node_modules/sharing-metrics/src/parser.js:8:15)
    at /Users/yau/Workspace/appleseed/node_modules/sharing-metrics/src/shares.js:81:26
    at Request._callback (/Users/yau/Workspace/appleseed/node_modules/sharing-metrics/src/shares.js:35:7)
    at Request.self.callback (/Users/yau/Workspace/appleseed/node_modules/sharing-metrics/node_modules/request/request.js:198:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (/Users/yau/Workspace/appleseed/node_modules/sharing-metrics/node_modules/request/request.js:1073:14)
    at emitOne (events.js:83:20)
    at Request.emit (events.js:170:7)
```

**Comment by codenameyau** [comment]
Looks like it's a dependency issue with the request module. Will remove dependency on it.

**Comment by codenameyau** [comment]
Well fuck, twitter has removed share counts from their API.

http://urls.api.twitter.com/2/urls/count.json?url=http://newsela.com
```
{"errors":[{"message":"Sorry, that page does not exist","code":34}]}
```

- http://searchenginewatch.com/sew/opinion/2436016/twitter-kills-share-counts-hands-end-of-dirty-stick-to-distributors
- https://warfareplugins.com/is-twitter-seriously-removing-share-counts-why-would-they-do-this/
